---
- name: Restart fail2ban
  ansible.builtin.systemd_service:
    name: fail2ban
    state: restarted
  failed_when: false

- name: Restart ssh
  ansible.builtin.systemd_service:
    name: ssh
    state: restarted
  failed_when: false
