apiVersion: v1
kind: Service
metadata:
  name: projects
  labels:
    app.kubernetes.io/name: projects
spec:
  selector:
    app.kubernetes.io/name: projects
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
