"""The Terraform layer (infra half of `suite apply`, ADR-038/042).

Wraps `terraform`/`tofu` in `terraform/environments/<provider>/`. Provider
parameters (project ids, ssh key) are prompted ONCE into `terraform.tfvars`;
everything suite.yaml implies (domain, firewall flags, bucket list) is written
to `suite.auto.tfvars` on every run — terraform auto-loads it, so enabling Meet
or the Mailbox opens its ports without hand-editing tfvars. Outputs land in the
machine state (`.suite-state.json`): the SSH target, the non-secret S3 config,
and the provider-minted secrets that cannot be derived from the seed.
"""

from __future__ import annotations

import json
import os
import shutil
import sys
from pathlib import Path

from . import prompt, spec, state
from .errors import SuiteError
from .process import run

PROVIDERS = ("scaleway",)
ENV_ROOT = "terraform/environments"
INVENTORY = "ansible/inventory/hosts.yml"
TEM_RELAY_HOST = "smtp.tem.scaleway.com:2587"  # Scaleway blocks 25/465/587 (ADR-038)


def ensure_infra(sp, st, *, assume_yes=False, plan_only=False):
    """Reconcile the Terraform layer to suite.yaml. Skipped when the derived
    inputs are unchanged since the last apply; returns True when an apply ran.
    (A hand edit of terraform.tfvars is applied on the next input change — run
    the terraform CLI directly for a pure provider-param change.)"""
    provider = sp.provider
    desired = spec.tfvars_for(sp)
    if st.get("provisioned") and st.get("provider") == provider \
            and st.get("tfvars") == desired:
        print("  infra: up to date")
        return False

    tf = _tf_bin()
    env_dir = f"{ENV_ROOT}/{provider}"
    tfvars = Path(env_dir) / "terraform.tfvars"
    if not tfvars.exists():
        if not sys.stdin.isatty():
            raise SuiteError(
                f"{tfvars} not found — run `suite apply` interactively once (or "
                "write it by hand) to set the provider parameters."
            )
        tfvars.write_text(_tfvars_text(_prompt_provider_params(provider)))
        print(f"\n==> Wrote {tfvars} (provider parameters — edit there, not here)")
    # Derived values override terraform.tfvars (terraform loads *.auto.tfvars last).
    Path(env_dir, "suite.auto.tfvars").write_text(
        "# Generated by `suite apply` from suite.yaml on every run — do not edit.\n"
        + _tfvars_text(desired)
    )

    _warn_missing_creds(provider)
    verb = "Planning" if plan_only else "Reconciling"
    print(f"\n==> {verb} the infrastructure (terraform, {provider})")
    run([tf, f"-chdir={env_dir}", "init"], step="terraform init")
    run([tf, f"-chdir={env_dir}", "plan"], step="terraform plan")
    if plan_only:
        return False
    if not assume_yes and not prompt.confirm("Apply this Terraform plan?", default=False):
        raise SuiteError("aborted before the Terraform apply")
    run([tf, f"-chdir={env_dir}", "apply", "-auto-approve"], step="terraform apply")

    proc = run([tf, f"-chdir={env_dir}", "output", "-json"], capture=True,
               step="terraform output")
    outputs = json.loads(proc.stdout or "{}")

    st["env"] = {**st.get("env", {}), **_env_from_outputs(outputs),
                 **_secrets_from_outputs(outputs)}
    st["ssh"] = _out(outputs, "ssh_target") or st.get("ssh", "")
    st["provider"] = provider
    st["tfvars"] = desired
    st["provisioned"] = True
    state.save(st)
    print(f"\n==> Stored the infra outputs in {state.path()}")
    if st["ssh"]:
        write_inventory(st["ssh"])
    _secret_banner(outputs)
    return True


def write_inventory(ssh_target):
    Path(INVENTORY).parent.mkdir(parents=True, exist_ok=True)
    Path(INVENTORY).write_text(_inventory_yaml(ssh_target))
    print(f"==> Wrote Ansible inventory to {INVENTORY} ({ssh_target})")


# --- terraform.tfvars generation -------------------------------------------------

def _prompt_provider_params(provider):
    """Provider parameters terraform cannot derive from suite.yaml, prompted once.
    Other vars keep their variables.tf defaults (region/zone/type/image) — edit
    terraform.tfvars to override."""
    common = [
        ("name", "Deployment name / slug (prefixes resources)", ""),
        ("ssh_public_key", "SSH public key (OpenSSH)", _default_ssh_key()),
    ]
    fields = [
        ("project_id", "Scaleway project ID", ""),
        ("organization_id", "Scaleway organization ID (IAM is org-scoped)", ""),
        *common,
    ]
    return {key: prompt.text(label, default=default) for key, label, default in fields}


def _tfvars_text(values):
    return "".join(f"{k} = {_hcl(v)}\n" for k, v in values.items())


def _hcl(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, list):
        return "[" + ", ".join(_hcl(v) for v in value) + "]"
    if isinstance(value, (int, float)):
        return str(value)
    return '"' + str(value).replace('"', '\\"') + '"'


# --- output wiring ---------------------------------------------------------------

def _out(outputs, key):
    o = outputs.get(key)
    return o.get("value") if o else None


def _env_from_outputs(outputs):
    """Non-secret infra values for the machine state. Reuses Terraform's own
    `env_object_storage` snippet (the exact OWNSUITE_S3_* lines) rather than
    re-deriving them, so they can never drift from the module."""
    env = {}
    # Both snippets are `KEY=value` lines; env_backup is empty when no backup bucket.
    for name in ("env_object_storage", "env_backup"):
        snippet = _out(outputs, name)
        if snippet and "<no bucket" not in snippet:
            for line in snippet.splitlines():
                line = line.strip()
                if "=" in line and not line.startswith("#"):
                    k, v = line.split("=", 1)
                    env[k.strip()] = v.strip()
    return env


def _secrets_from_outputs(outputs):
    """External secrets (provider-minted S3 keys, relay account) that cannot be
    seed-derived, mapped to their OWNSUITE_* keys. Stored in the git-ignored
    machine state so apply/upgrade pick them up without a manual export."""
    env = {}
    ak, sk = _out(outputs, "s3_access_key"), _out(outputs, "s3_secret_key")
    if ak and sk:
        env["OWNSUITE_S3_ACCESS_KEY"] = ak
        env["OWNSUITE_S3_SECRET_KEY"] = sk
    # Off-site backup creds (null unless a backup bucket was provisioned). The rclone
    # crypt passphrase stays seed-derived, so it is not among these.
    bak, bsk = _out(outputs, "backup_s3_access_key"), _out(outputs, "backup_s3_secret_key")
    if bak and bsk:
        env["OWNSUITE_BACKUP_S3_ACCESS_KEY"] = bak
        env["OWNSUITE_BACKUP_S3_SECRET_KEY"] = bsk
    ru, rp = _out(outputs, "mta_relay_username"), _out(outputs, "mta_relay_password")
    if ru and rp:
        env["OWNSUITE_MTA_RELAY_USERNAME"] = ru
        env["OWNSUITE_MTA_RELAY_PASSWORD"] = rp
        env["OWNSUITE_MTA_RELAY_HOST"] = TEM_RELAY_HOST
    return env


def _inventory_yaml(ssh_target):
    user, sep, host = ssh_target.partition("@")
    if not sep:  # bare host, no user@ prefix
        user, host = "root", ssh_target
    return (
        "---\n"
        "# Written by `suite apply`. Single-node K3s = one host in `ownsuite`.\n"
        "ownsuite:\n"
        "  hosts:\n"
        "    vps:\n"
        f'      ansible_host: "{host}"\n'
        f'      ansible_user: "{user}"\n'
    )


def _secret_banner(outputs):
    """The provider-minted secrets live in the git-ignored machine state (above);
    this only reminds the operator to (a) also stash them in a password manager —
    the state file is disposable — and (b) publish the TEM email DNS records."""
    ak = _out(outputs, "s3_access_key")
    ru = _out(outputs, "mta_relay_username")
    if ak or ru:
        print(
            "\n" + "=" * 70 + "\n"
            "EXTERNAL SECRETS were stored in .suite-state.json (git-ignored) so apply\n"
            "and upgrade can read them. They cannot be derived from the seed — ALSO\n"
            "store them in your password manager; the state file is disposable.\n"
            + "=" * 70
        )
    tem_dns = _out(outputs, "tem_dns")
    if tem_dns:
        print("\n==> Also publish the TEM SPF/DKIM/DMARC records:\n" + str(tem_dns))


# --- helpers ---------------------------------------------------------------------

def _tf_bin():
    for cand in ("terraform", "tofu"):
        if shutil.which(cand):
            return cand
    raise SuiteError("neither `terraform` nor `tofu` found on PATH")


def _default_ssh_key():
    for name in ("id_ed25519.pub", "id_rsa.pub"):
        p = Path.home() / ".ssh" / name
        if p.exists():
            return p.read_text().strip()
    return ""


def _warn_missing_creds(provider):
    if provider == "scaleway":
        have_env = os.environ.get("SCW_ACCESS_KEY") and os.environ.get("SCW_SECRET_KEY")
        have_file = (Path.home() / ".config/scw/config.yaml").exists()
        if not (have_env or have_file):
            print("\nWARNING: SCW_ACCESS_KEY/SCW_SECRET_KEY not set and no "
                  "~/.config/scw/config.yaml — Terraform will fail to authenticate.")
