name: docs

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "requirements-docs.txt"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Cache MkDocs build artifacts
        uses: actions/cache@v6
        with:
          key: mkdocs-material-${{ github.sha }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements-docs.txt
      - run: mkdocs gh-deploy --force
